[build]
# Force building from this app's directory even if Netlify runs from repo root
command = "npm --prefix ./apps/poshpoule/buyer-app run build"
publish = "apps/poshpoule/buyer-app/.svelte-kit/netlify"
