[build]
# Install and build only this app from monorepo
base = "apps/poshpoule/buyer-app"
command = "npm run build"
publish = ".netlify"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"
  NODE_ENV = "development"
