[build]
  command = "npm ci --legacy-peer-deps && npm run build -w apps/zereth-foods"
  publish = "apps/zereth-foods/.next"

[build.environment]
  NODE_VERSION = "20.11.1"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
